name: Build Gradle project

on:
  pull_request:
    branches: ["main"]

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    services:
      keycloak:
        image: jornkersten/ajcompare:latest
        ports:
          - 8484:8484
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Run tests
        run: ./gradlew test
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
